site_name: mdotoolbox
theme:
  name: material

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          paths: [src]

markdown_extensions:
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

nav:
  - Home: index.md
  - Tutorial: tutorial.md
  - Guides:
      - MDO Structure: guides/mdo_structure.md
      - Mathematical Foundation: guides/math.md
  - Frameworks:
      - CO: frameworks/co.md
      - BACO: frameworks/baco.md
  - API Reference:
      - Index: api/index.md
      - Core Base API: api/core.md
  - Contributing: CONTRIBUTING.md
  - License: LICENSE.md
